"use client";

import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../../components/Header";
import { useRouter } from "next/router";
import { Address } from "viem";

import Crowdfounding from "../../abi/Crowdfunding.json";
import { useReadContract } from "wagmi";
import CampaignContainer from "../../components/CampaignContainer";

const CampaignDetail: NextPage = () => {
  const router = useRouter();
  const { campaignId } = router.query;

  const { data: campaign, isLoading: campaignLoading } = useReadContract({
    address: process.env.NEXT_PUBLIC_CONTRACT as Address,
    abi: Crowdfounding.abi,
    functionName: "campaigns",
    args: [Number(campaignId) - 1],
  });

  const { data: milestones, isLoading: milestonesLoading } = useReadContract({
    address: process.env.NEXT_PUBLIC_CONTRACT as Address,
    abi: Crowdfounding.abi,
    functionName: "getMilestones",
    args: [Number(campaignId) - 1],
  });

  const { data: campaignContribution, isLoading: campaignContributionLoading } =
    useReadContract({
      address: process.env.NEXT_PUBLIC_CONTRACT as Address,
      abi: Crowdfounding.abi,
      functionName: "totalCampaignContribution",
      args: [Number(campaignId) - 1],
    });

  console.log("milestones: ", milestones);

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Header />

      <main>
        <section>
          <div className="container mx-auto pt-10">
            {(campaign as string[]) && (
              <CampaignContainer
                index={Number(campaignId) - 1}
                campaign={campaign as string[]}
                detail={true}
                milestones={milestones as any[]}
                campaignContribution={campaignContribution as number}
              />
            )}
          </div>
        </section>
      </main>
    </div>
  );
};

export default CampaignDetail;
