"use client";

import type { NextPage } from "next";
import Head from "next/head";

import { Header } from "../../components/Header";
import { useParams } from "next/navigation";

const CampaignDetail: NextPage = () => {
  //   const { id } = useParams() as { id: string };

  const { campaign_id } = useParams<{ campaign_id: string }>();

  return (
    <div>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Header />

      <main>
        {/* <Campaigns /> */}
        {campaign_id}
      </main>
    </div>
  );
};

export default CampaignDetail;
